name: Validar Script Shell

on:
  push:
    branches: [ "main" ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Validar script
        run: shellcheck validar.sh
